url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Приглашение на день рождения!"
lang: ru # the languaje of your site, e.g. en-EN
theme_custom: yellow-black-pacifico # the name of your theme, e.g. gree-white, gray-white, indigo-white, indigo-white-pacifico, etc.
theme_extension_background: jpg # the extension name of your background file, e.g. png
theme_name_background: birthday
# author: Rolly # the name of author, show in the home page "Hello, I'm *author*" and seo.
description: Birthday party invitation
tagline: *description
twitter:
  username: pwnakil # your user of twitter account.
  card: summary
title_intro: Приглашение на день рождения!
skill_separator: "" # the separator symbol to your skill at home page.
# title_plataforms: Connect with me on # keep empty for don't show title on plataforms icon.
forkme: false # true or false to show or hide forkme button.
forkme_link: https://github.com/rollys/jekyll-dev-landing-page # link of repository fork.

# Build settings
plugins:
  - jekyll-seo-tag

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
